# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'LonestarGuestAssistantCasino' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    installer.pods_project.targets.each do |target|
      next unless target.name == 'fmt'

      target.build_configurations.each do |build_config|
        build_config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'

        definitions = build_config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] || ['$(inherited)']
        definitions = [definitions] if definitions.is_a?(String)
        definitions << 'FMT_USE_CONSTEVAL=0' unless definitions.include?('FMT_USE_CONSTEVAL=0')
        build_config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = definitions
      end
    end

    fmt_header_paths = [
      'fmt/include/fmt/base.h',
      'Headers/Public/fmt/fmt/base.h',
      'Headers/Private/fmt/fmt/base.h',
    ]

    fmt_header_paths
      .map { |header_path| File.realpath(File.join(installer.sandbox.root.to_s, header_path)) rescue nil }
      .compact
      .uniq
      .each do |absolute_path|
      next unless File.exist?(absolute_path)

      header = File.read(absolute_path)
      patched_header = header.gsub(/#\s*define\s+FMT_USE_CONSTEVAL\s+1/, '#  define FMT_USE_CONSTEVAL 0')
      if patched_header != header
        File.chmod(0o644, absolute_path) unless File.writable?(absolute_path)
        File.write(absolute_path, patched_header)
      end
    end
  end
end
