import {images} from '../../../assets/guest-atlas';
import type {MenuCategory, MenuItem} from '../types';

export const menuCategories: MenuCategory[] = [
  'Breakfast',
  'Starters',
  'Main Courses',
  'Desserts',
  'Drinks',
];

export const menuItems: MenuItem[] = [
  {
    id: 'resort-sunrise-omelette',
    name: 'Resort Sunrise Omelette',
    category: 'Breakfast',
    ingredients: 'Eggs, cheddar cheese, spinach, cherry tomatoes, herbs',
    price: 12,
    image: images.dishSunriseOmelette,
  },
  {
    id: 'avocado-toast-deluxe',
    name: 'Avocado Toast Deluxe',
    category: 'Breakfast',
    ingredients: 'Sourdough bread, avocado, poached egg, microgreens',
    price: 14,
    image: images.dishAvocadoToast,
  },
  {
    id: 'berry-yogurt-bowl',
    name: 'Berry Yogurt Bowl',
    category: 'Breakfast',
    ingredients: 'Greek yogurt, mixed berries, granola, honey',
    price: 10,
    image: images.dishBerryYogurt,
  },
  {
    id: 'pancake-stack',
    name: 'Pancake Stack',
    category: 'Breakfast',
    ingredients: 'Buttermilk pancakes, maple syrup, fresh berries',
    price: 13,
    image: images.dishPancakeStack,
  },
  {
    id: 'mediterranean-bruschetta',
    name: 'Mediterranean Bruschetta',
    category: 'Starters',
    ingredients: 'Toasted bread, tomatoes, basil, olive oil, parmesan',
    price: 11,
    image: images.dishBruschetta,
  },
  {
    id: 'crispy-calamari',
    name: 'Crispy Calamari',
    category: 'Starters',
    ingredients: 'Squid rings, lemon aioli, herbs',
    price: 16,
    image: images.dishCalamari,
  },
  {
    id: 'shrimp-cocktail',
    name: 'Shrimp Cocktail',
    category: 'Starters',
    ingredients: 'Chilled shrimp, cocktail sauce, lemon',
    price: 18,
    image: images.dishShrimpCocktail,
  },
  {
    id: 'burrata-caprese',
    name: 'Burrata Caprese',
    category: 'Starters',
    ingredients: 'Burrata cheese, tomatoes, basil, balsamic glaze',
    price: 15,
    image: images.dishBurrata,
  },
  {
    id: 'grilled-salmon-fillet',
    name: 'Grilled Salmon Fillet',
    category: 'Main Courses',
    ingredients: 'Atlantic salmon, asparagus, lemon butter sauce',
    price: 28,
    image: images.dishSalmon,
  },
  {
    id: 'premium-ribeye-steak',
    name: 'Premium Ribeye Steak',
    category: 'Main Courses',
    ingredients: 'Ribeye steak, roasted potatoes, seasonal vegetables',
    price: 36,
    image: images.dishRibeye,
  },
  {
    id: 'truffle-mushroom-risotto',
    name: 'Truffle Mushroom Risotto',
    category: 'Main Courses',
    ingredients: 'Arborio rice, mushrooms, parmesan, truffle oil',
    price: 24,
    image: images.dishRisotto,
  },
  {
    id: 'herb-roasted-chicken',
    name: 'Herb Roasted Chicken',
    category: 'Main Courses',
    ingredients: 'Chicken breast, mashed potatoes, rosemary gravy',
    price: 25,
    image: images.dishChicken,
  },
  {
    id: 'chocolate-lava-cake',
    name: 'Chocolate Lava Cake',
    category: 'Desserts',
    ingredients: 'Dark chocolate cake, vanilla ice cream',
    price: 12,
    image: images.dessertLavaCake,
  },
  {
    id: 'new-york-cheesecake',
    name: 'New York Cheesecake',
    category: 'Desserts',
    ingredients: 'Cream cheese, biscuit crust, berry sauce',
    price: 11,
    image: images.dessertCheesecake,
  },
  {
    id: 'tiramisu-classico',
    name: 'Tiramisu Classico',
    category: 'Desserts',
    ingredients: 'Mascarpone, espresso, cocoa powder',
    price: 10,
    image: images.dessertTiramisu,
  },
  {
    id: 'tropical-fruit-parfait',
    name: 'Tropical Fruit Parfait',
    category: 'Desserts',
    ingredients: 'Mango, pineapple, yogurt, mint',
    price: 9,
    image: images.dessertFruitParfait,
  },
  {
    id: 'emerald-mojito',
    name: 'Emerald Mojito',
    category: 'Drinks',
    ingredients: 'Mint, lime, sparkling water, cane sugar',
    price: 8,
    image: images.drinkMojito,
  },
  {
    id: 'signature-resort-smoothie',
    name: 'Signature Resort Smoothie',
    category: 'Drinks',
    ingredients: 'Banana, mango, pineapple, coconut milk',
    price: 9,
    image: images.drinkSmoothie,
  },
  {
    id: 'iced-caramel-latte',
    name: 'Iced Caramel Latte',
    category: 'Drinks',
    ingredients: 'Espresso, milk, caramel syrup, ice',
    price: 7,
    image: images.drinkLatte,
  },
  {
    id: 'fresh-citrus-cooler',
    name: 'Fresh Citrus Cooler',
    category: 'Drinks',
    ingredients: 'Orange juice, grapefruit juice, sparkling water',
    price: 8,
    image: images.drinkCooler,
  },
];
